export var FOODS = [
  {cat:"Fruit",name:"Apple (medium)",serv:"1 medium",cal:95,pro:0,carb:25,fat:0,fib:4,sug:19},
  {cat:"Fruit",name:"Banana",serv:"1 medium",cal:105,pro:1,carb:27,fat:0,fib:3,sug:14},
  {cat:"Fruit",name:"Orange",serv:"1 medium",cal:62,pro:1,carb:15,fat:0,fib:3,sug:12},
  {cat:"Fruit",name:"Strawberries",serv:"1 cup",cal:49,pro:1,carb:12,fat:0,fib:3,sug:7},
  {cat:"Fruit",name:"Blueberries",serv:"1 cup",cal:84,pro:1,carb:21,fat:0,fib:4,sug:15},
  {cat:"Fruit",name:"Raspberries",serv:"1 cup",cal:64,pro:1,carb:15,fat:1,fib:8,sug:5},
  {cat:"Fruit",name:"Blackberries",serv:"1 cup",cal:62,pro:2,carb:14,fat:1,fib:8,sug:7},
  {cat:"Fruit",name:"Cherries",serv:"1 cup",cal:87,pro:1,carb:22,fat:0,fib:3,sug:18},
  {cat:"Fruit",name:"Grapes",serv:"1 cup",cal:104,pro:1,carb:27,fat:0,fib:1,sug:23},
  {cat:"Fruit",name:"Watermelon",serv:"1 cup diced",cal:46,pro:1,carb:12,fat:0,fib:1,sug:9},
  {cat:"Fruit",name:"Cantaloupe",serv:"1 cup diced",cal:54,pro:1,carb:13,fat:0,fib:1,sug:12},
  {cat:"Fruit",name:"Mango",serv:"1 cup",cal:99,pro:1,carb:25,fat:1,fib:3,sug:23},
  {cat:"Fruit",name:"Pineapple",serv:"1 cup",cal:82,pro:1,carb:22,fat:0,fib:2,sug:16},
  {cat:"Fruit",name:"Avocado",serv:"1/2 medium",cal:120,pro:1,carb:6,fat:11,fib:5,sug:0},
  {cat:"Fruit",name:"Peach",serv:"1 medium",cal:59,pro:1,carb:14,fat:0,fib:2,sug:13},
  {cat:"Fruit",name:"Pear",serv:"1 medium",cal:101,pro:1,carb:27,fat:0,fib:6,sug:17},
  {cat:"Fruit",name:"Kiwi",serv:"1 medium",cal:42,pro:1,carb:10,fat:0,fib:2,sug:6},
  {cat:"Fruit",name:"Grapefruit",serv:"1/2 medium",cal:52,pro:1,carb:13,fat:0,fib:2,sug:8},
  {cat:"Fruit",name:"Plum",serv:"1 medium",cal:30,pro:0,carb:8,fat:0,fib:1,sug:7},
  {cat:"Vegetable",name:"Broccoli",serv:"1 cup",cal:55,pro:4,carb:11,fat:1,fib:5,sug:2},
  {cat:"Vegetable",name:"Spinach (raw)",serv:"2 cups",cal:14,pro:2,carb:2,fat:0,fib:1,sug:0},
  {cat:"Vegetable",name:"Sweet Potato",serv:"1 medium",cal:103,pro:2,carb:24,fat:0,fib:4,sug:7},
  {cat:"Vegetable",name:"Potato (baked)",serv:"1 medium",cal:161,pro:4,carb:37,fat:0,fib:4,sug:2},
  {cat:"Vegetable",name:"Carrots",serv:"1 cup",cal:52,pro:1,carb:12,fat:0,fib:4,sug:6},
  {cat:"Vegetable",name:"Green Beans",serv:"1 cup",cal:31,pro:2,carb:7,fat:0,fib:3,sug:3},
  {cat:"Vegetable",name:"Asparagus",serv:"6 spears",cal:20,pro:2,carb:4,fat:0,fib:2,sug:1},
  {cat:"Vegetable",name:"Bell Pepper",serv:"1 medium",cal:31,pro:1,carb:7,fat:0,fib:2,sug:5},
  {cat:"Vegetable",name:"Tomato",serv:"1 medium",cal:22,pro:1,carb:5,fat:0,fib:1,sug:3},
  {cat:"Vegetable",name:"Corn on Cob",serv:"1 ear",cal:88,pro:3,carb:19,fat:1,fib:2,sug:6},
  {cat:"Vegetable",name:"Cauliflower",serv:"1 cup",cal:27,pro:2,carb:5,fat:0,fib:2,sug:2},
  {cat:"Vegetable",name:"Zucchini",serv:"1 cup",cal:17,pro:1,carb:3,fat:0,fib:1,sug:3},
  {cat:"Vegetable",name:"Cucumber",serv:"1 cup",cal:16,pro:1,carb:4,fat:0,fib:1,sug:2},
  {cat:"Vegetable",name:"Kale",serv:"1 cup",cal:33,pro:3,carb:6,fat:1,fib:1,sug:2},
  {cat:"Vegetable",name:"Brussels Sprouts",serv:"1 cup",cal:56,pro:4,carb:11,fat:1,fib:4,sug:3},
  {cat:"Vegetable",name:"Celery",serv:"2 stalks",cal:13,pro:1,carb:3,fat:0,fib:1,sug:1},
  {cat:"Vegetable",name:"Mushrooms",serv:"1 cup",cal:21,pro:3,carb:3,fat:0,fib:1,sug:2},
  {cat:"Vegetable",name:"Edamame",serv:"1 cup",cal:188,pro:18,carb:14,fat:8,fib:8,sug:3},
  {cat:"Vegetable",name:"Beets",serv:"1 cup",cal:58,pro:2,carb:13,fat:0,fib:4,sug:9},
  {cat:"Chicken",name:"Chicken Breast (grilled)",serv:"6 oz",cal:281,pro:53,carb:0,fat:6,fib:0,sug:0},
  {cat:"Chicken",name:"Chicken Breast (fried)",serv:"6 oz",cal:390,pro:46,carb:12,fat:17,fib:0,sug:0},
  {cat:"Chicken",name:"Chicken Thigh (grilled)",serv:"1 thigh",cal:230,pro:28,carb:0,fat:13,fib:0,sug:0},
  {cat:"Chicken",name:"Chicken Thigh (fried)",serv:"1 thigh",cal:318,pro:25,carb:9,fat:20,fib:0,sug:0},
  {cat:"Chicken",name:"Chicken Wing (3)",serv:"3 wings",cal:320,pro:27,carb:0,fat:23,fib:0,sug:0},
  {cat:"Chicken",name:"Chicken Drumstick (2)",serv:"2 drumsticks",cal:296,pro:36,carb:0,fat:16,fib:0,sug:0},
  {cat:"Chicken",name:"Chicken Tenders (fried)",serv:"4 pieces",cal:360,pro:28,carb:20,fat:18,fib:1,sug:1},
  {cat:"Chicken",name:"Rotisserie Chicken",serv:"6 oz",cal:310,pro:42,carb:0,fat:15,fib:0,sug:0},
  {cat:"Beef",name:"Ribeye Steak",serv:"8 oz",cal:544,pro:48,carb:0,fat:38,fib:0,sug:0},
  {cat:"Beef",name:"Sirloin Steak",serv:"8 oz",cal:408,pro:52,carb:0,fat:21,fib:0,sug:0},
  {cat:"Beef",name:"Filet Mignon",serv:"6 oz",cal:348,pro:42,carb:0,fat:18,fib:0,sug:0},
  {cat:"Beef",name:"Ground Beef 80/20",serv:"6 oz",cal:426,pro:38,carb:0,fat:30,fib:0,sug:0},
  {cat:"Beef",name:"Ground Beef 90/10",serv:"6 oz",cal:332,pro:42,carb:0,fat:18,fib:0,sug:0},
  {cat:"Beef",name:"Chuck Roast",serv:"6 oz",cal:396,pro:42,carb:0,fat:24,fib:0,sug:0},
  {cat:"Beef",name:"Brisket",serv:"6 oz",cal:408,pro:40,carb:0,fat:27,fib:0,sug:0},
  {cat:"Beef",name:"NY Strip",serv:"8 oz",cal:480,pro:50,carb:0,fat:30,fib:0,sug:0},
  {cat:"Beef",name:"T-Bone",serv:"8 oz",cal:496,pro:46,carb:0,fat:34,fib:0,sug:0},
  {cat:"Pork",name:"Pork Chop (grilled)",serv:"6 oz",cal:310,pro:42,carb:0,fat:15,fib:0,sug:0},
  {cat:"Pork",name:"Pork Tenderloin",serv:"6 oz",cal:248,pro:44,carb:0,fat:7,fib:0,sug:0},
  {cat:"Pork",name:"Pulled Pork",serv:"6 oz",cal:380,pro:36,carb:8,fat:22,fib:0,sug:6},
  {cat:"Pork",name:"Bacon (3 slices)",serv:"3 slices",cal:129,pro:9,carb:0,fat:10,fib:0,sug:0},
  {cat:"Pork",name:"Baby Back Ribs",serv:"6 ribs",cal:540,pro:36,carb:0,fat:42,fib:0,sug:0},
  {cat:"Pork",name:"Pork Loin Roast",serv:"6 oz",cal:270,pro:44,carb:0,fat:10,fib:0,sug:0},
  {cat:"Fish",name:"Salmon Fillet",serv:"6 oz",cal:354,pro:38,carb:0,fat:22,fib:0,sug:0},
  {cat:"Fish",name:"Tuna Steak",serv:"6 oz",cal:244,pro:52,carb:0,fat:2,fib:0,sug:0},
  {cat:"Fish",name:"Tilapia",serv:"6 oz",cal:218,pro:44,carb:0,fat:4,fib:0,sug:0},
  {cat:"Fish",name:"Cod",serv:"6 oz",cal:186,pro:40,carb:0,fat:2,fib:0,sug:0},
  {cat:"Fish",name:"Shrimp",serv:"6 oz",cal:168,pro:36,carb:0,fat:2,fib:0,sug:0},
  {cat:"Fish",name:"Catfish (grilled)",serv:"6 oz",cal:230,pro:38,carb:0,fat:8,fib:0,sug:0},
  {cat:"Fish",name:"Trout",serv:"6 oz",cal:280,pro:38,carb:0,fat:12,fib:0,sug:0},
  {cat:"Fish",name:"Walleye",serv:"6 oz",cal:196,pro:40,carb:0,fat:3,fib:0,sug:0},
  {cat:"Other",name:"Eggs (2 whole)",serv:"2 large",cal:143,pro:12,carb:1,fat:10,fib:0,sug:1},
  {cat:"Other",name:"Egg Whites (3)",serv:"3 whites",cal:51,pro:11,carb:0,fat:0,fib:0,sug:0},
  {cat:"Other",name:"White Rice",serv:"1 cup",cal:206,pro:4,carb:45,fat:0,fib:1,sug:0},
  {cat:"Other",name:"Brown Rice",serv:"1 cup",cal:216,pro:5,carb:45,fat:2,fib:4,sug:1},
  {cat:"Other",name:"Pasta",serv:"1 cup",cal:220,pro:8,carb:43,fat:1,fib:3,sug:1},
  {cat:"Other",name:"Oatmeal",serv:"1 cup",cal:166,pro:6,carb:28,fat:4,fib:4,sug:1},
  {cat:"Other",name:"Peanut Butter",serv:"2 tbsp",cal:190,pro:7,carb:7,fat:16,fib:2,sug:3},
  {cat:"Other",name:"Greek Yogurt",serv:"1 cup",cal:130,pro:22,carb:9,fat:0,fib:0,sug:7},
  {cat:"Other",name:"Protein Shake",serv:"1 scoop",cal:120,pro:24,carb:3,fat:1,fib:0,sug:1},
  {cat:"Other",name:"Black Beans",serv:"1/2 cup",cal:114,pro:8,carb:20,fat:0,fib:8,sug:0},
  {cat:"Other",name:"Quinoa",serv:"1 cup",cal:222,pro:8,carb:39,fat:4,fib:5,sug:2},
  {cat:"Other",name:"Turkey Breast",serv:"4 oz",cal:120,pro:24,carb:2,fat:1,fib:0,sug:1},
  {cat:"Other",name:"Venison",serv:"6 oz",cal:258,pro:50,carb:0,fat:6,fib:0,sug:0}
];

export var CATS = ["Fruit","Vegetable","Chicken","Beef","Pork","Fish","Other"];
export var DAYNAMES = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
export var SPORTS = [
  {id:"triathlon",name:"Triathlon",disc:["swim","bike","run"],icon:"S/B/R"},
  {id:"duathlon",name:"Duathlon",disc:["bike","run"],icon:"B/R"},
  {id:"aquathlon",name:"Aquathlon",disc:["swim","run"],icon:"S/R"},
  {id:"marathon",name:"Marathon / Running",disc:["run"],icon:"RUN"},
  {id:"ultra",name:"Ultra Marathon",disc:["run"],icon:"ULTRA"},
  {id:"cycling",name:"Century / Cycling",disc:["bike"],icon:"BIKE"},
  {id:"swim",name:"Open Water / Swim",disc:["swim"],icon:"SWIM"}
];
export var RACE_TYPES = {
  triathlon:["Super Sprint Tri","Sprint Tri","Olympic Tri","Half Ironman 70.3","Ironman 140.6"],
  duathlon:["Sprint Du","Standard Du","Long Du","Powerman"],
  aquathlon:["Sprint Aquathlon","Standard Aquathlon","Long Aquathlon"],
  marathon:["5K","10K","15K","10 Mile","Half Marathon","Marathon"],
  ultra:["50K","50 Mile","100K","100 Mile","24 Hour","Backyard Ultra"],
  cycling:["25 Mile","50 Mile","Metric Century (62mi)","Century (100mi)","Double Century","Gran Fondo"],
  swim:["1 Mile","1.2 Mile","2.4 Mile","5K Swim","10K Swim"]
};
export var TERRAIN_OPTS = ["Flat","Rolling hills","Hilly","Mountainous","Mixed","Trail/Off-road","Track","Unknown"];
export var SWIM_TYPE_OPTS = ["Open water - lake","Open water - ocean","Open water - river (downstream)","Open water - river (upstream)","Pool","Unknown"];
export var BODY_TYPES = [{v:"slim",l:"Slim / Lean"},{v:"athletic",l:"Athletic / Muscular"},{v:"average",l:"Average Build"},{v:"stocky",l:"Stocky / Heavy-set"},{v:"large",l:"Large / Big-boned"}];
export var TIERS = {
  trial: { name: "Free Trial", price: 0, maxRaces: 0, maxMods: 0, hasPlanBuilder: false, hasCoach: false, durationDays: 7 },
  basic: { name: "Basic", price: 9.99, maxRaces: 5, maxMods: 5, hasPlanBuilder: true, hasCoach: true, smsPrice: 3.99 },
  pro: { name: "Pro", price: 16.99, maxRaces: 15, maxMods: 15, hasPlanBuilder: true, hasCoach: true, smsPrice: 2.99 }
};
export var SMS_PRICE = 3.99;
export var SMS_TRIAL_DAYS = 3;
